/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vn_com_vng_zalopay_sound_transcoder_Decoder */

#ifndef _Included_vn_com_vng_zalopay_sound_transcoder_Decoder
#define _Included_vn_com_vng_zalopay_sound_transcoder_Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vn_com_vng_zalopay_sound_transcoder_Decoder
 * Method:    initializeDecoder
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_vn_com_vng_zalopay_sound_transcoder_Decoder_initializeDecoder
  (JNIEnv *, jobject);

/*
 * Class:     vn_com_vng_zalopay_sound_transcoder_Decoder
 * Method:    processBuffer
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_vn_com_vng_zalopay_sound_transcoder_Decoder_processBuffer
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     vn_com_vng_zalopay_sound_transcoder_Decoder
 * Method:    releaseDecoder
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_vn_com_vng_zalopay_sound_transcoder_Decoder_releaseDecoder
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class vn_com_vng_zalopay_sound_transcoder_Decoder_DecoderListener */

#ifndef _Included_vn_com_vng_zalopay_sound_transcoder_Decoder_DecoderListener
#define _Included_vn_com_vng_zalopay_sound_transcoder_Decoder_DecoderListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
