package vn.com.vng.zalopay.data.cache.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "APP_RESOURCE_GD".
 */
public class AppResourceGD {

    private int appid;
    private String appname;
    private Integer needdownloadrs;
    private String imageurl;
    private String jsurl;
    private Integer status;
    private String checksum;
    private Boolean download;

    public AppResourceGD() {
    }

    public AppResourceGD(int appid, String appname, Integer needdownloadrs, String imageurl, String jsurl, Integer status, String checksum, Boolean download) {
        this.appid = appid;
        this.appname = appname;
        this.needdownloadrs = needdownloadrs;
        this.imageurl = imageurl;
        this.jsurl = jsurl;
        this.status = status;
        this.checksum = checksum;
        this.download = download;
    }

    public int getAppid() {
        return appid;
    }

    public void setAppid(int appid) {
        this.appid = appid;
    }

    public String getAppname() {
        return appname;
    }

    public void setAppname(String appname) {
        this.appname = appname;
    }

    public Integer getNeeddownloadrs() {
        return needdownloadrs;
    }

    public void setNeeddownloadrs(Integer needdownloadrs) {
        this.needdownloadrs = needdownloadrs;
    }

    public String getImageurl() {
        return imageurl;
    }

    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    public String getJsurl() {
        return jsurl;
    }

    public void setJsurl(String jsurl) {
        this.jsurl = jsurl;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getChecksum() {
        return checksum;
    }

    public void setChecksum(String checksum) {
        this.checksum = checksum;
    }

    public Boolean getDownload() {
        return download;
    }

    public void setDownload(Boolean download) {
        this.download = download;
    }

}
