package vn.com.vng.zalopay.data.cache.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "APP_RESOURCE_GD".
 */
@Entity
public class AppResourceGD {

    @Unique
    public int appid;
    public String appname;
    public Integer needdownloadrs;
    public String imageurl;
    public String jsurl;
    public Integer status;
    public String checksum;
    public Integer apptype;
    public String weburl;
    public String iconurl;
    public Integer sortOrder;
    public Integer stateDownload;
    public Long timeDownload;
    public Integer numRetry;


}
