package vn.com.vng.zalopay.data.cache.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "APPTRANSID_LOG_GD".
 */
@Entity
public class ApptransidLogGD {

    @Id
    @NotNull
    @Unique
    public String apptransid;
    public Integer appid;
    public Integer step;
    public Integer step_result;
    public Integer pcmid;
    public Integer transtype;
    public Long transid;
    public Integer sdk_result;
    public Integer server_result;
    public String source;


}
