package vn.com.vng.zalopay.data.cache.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BUNDLE_GD".
 */
public class BundleGD {

    private long id;
    private Long lastTimeGetPackage;

    public BundleGD() {
    }

    public BundleGD(long id) {
        this.id = id;
    }

    public BundleGD(long id, Long lastTimeGetPackage) {
        this.id = id;
        this.lastTimeGetPackage = lastTimeGetPackage;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Long getLastTimeGetPackage() {
        return lastTimeGetPackage;
    }

    public void setLastTimeGetPackage(Long lastTimeGetPackage) {
        this.lastTimeGetPackage = lastTimeGetPackage;
    }

}
