package vn.com.vng.zalopay.data.cache.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CONTACT_GD".
 */
@Entity
public class ContactGD {
    public String fulltextsearch;
    public String displayName;

    @Id
    public long phoneNumber;


}
