package vn.com.vng.zalopay.data.cache.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PAYMENT_TRANS_TYPE_GD".
 */
@Entity(indexes = {
    @Index(value = "transtype, pmcid", unique = true)
})
public class PaymentTransTypeGD {

    @Id
    public long transtype;
    public long pmcid;
    public String pmcname;
    public Long status;
    public Long minvalue;
    public Long maxvalue;
    public Float feerate;
    public Long minfee;
    public String feecaltype;


}
