package vn.com.vng.zalopay.data.cache.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import vn.com.vng.zalopay.data.cache.model.ReceiveBundleGD;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RECEIVE_BUNDLE_GD".
*/
public class ReceiveBundleGDDao extends AbstractDao<ReceiveBundleGD, Long> {

    public static final String TABLENAME = "RECEIVE_BUNDLE_GD";

    /**
     * Properties of entity ReceiveBundleGD.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Type = new Property(1, Integer.class, "type", false, "TYPE");
        public final static Property CreateTime = new Property(2, Long.class, "createTime", false, "CREATE_TIME");
        public final static Property TotalLuck = new Property(3, Integer.class, "totalLuck", false, "TOTAL_LUCK");
        public final static Property NumOfOpenedPakages = new Property(4, Integer.class, "numOfOpenedPakages", false, "NUM_OF_OPENED_PAKAGES");
        public final static Property NumOfPackages = new Property(5, Integer.class, "numOfPackages", false, "NUM_OF_PACKAGES");
    };

    private DaoSession daoSession;


    public ReceiveBundleGDDao(DaoConfig config) {
        super(config);
    }
    
    public ReceiveBundleGDDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECEIVE_BUNDLE_GD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL UNIQUE ," + // 0: id
                "\"TYPE\" INTEGER," + // 1: type
                "\"CREATE_TIME\" INTEGER," + // 2: createTime
                "\"TOTAL_LUCK\" INTEGER," + // 3: totalLuck
                "\"NUM_OF_OPENED_PAKAGES\" INTEGER," + // 4: numOfOpenedPakages
                "\"NUM_OF_PACKAGES\" INTEGER);"); // 5: numOfPackages
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECEIVE_BUNDLE_GD\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ReceiveBundleGD entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(2, type);
        }
 
        Long createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(3, createTime);
        }
 
        Integer totalLuck = entity.getTotalLuck();
        if (totalLuck != null) {
            stmt.bindLong(4, totalLuck);
        }
 
        Integer numOfOpenedPakages = entity.getNumOfOpenedPakages();
        if (numOfOpenedPakages != null) {
            stmt.bindLong(5, numOfOpenedPakages);
        }
 
        Integer numOfPackages = entity.getNumOfPackages();
        if (numOfPackages != null) {
            stmt.bindLong(6, numOfPackages);
        }
    }

    @Override
    protected void attachEntity(ReceiveBundleGD entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ReceiveBundleGD readEntity(Cursor cursor, int offset) {
        ReceiveBundleGD entity = new ReceiveBundleGD( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // type
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // createTime
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // totalLuck
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // numOfOpenedPakages
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5) // numOfPackages
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ReceiveBundleGD entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setType(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setCreateTime(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setTotalLuck(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setNumOfOpenedPakages(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setNumOfPackages(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ReceiveBundleGD entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ReceiveBundleGD entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
