package vn.com.vng.zalopay.data.cache.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "RECEIVE_PACKET_SUMMARY_DB".
 */
@Entity
public class ReceivePacketSummaryDB {

    @Id
    private Long id;
    private Long totalOfRevamount;
    private Integer totalOfRevPackage;
    private Integer totalOfLuckiestDraw;
    private Long timeCreate;

    @Generated
    public ReceivePacketSummaryDB() {
    }

    public ReceivePacketSummaryDB(Long id) {
        this.id = id;
    }

    @Generated
    public ReceivePacketSummaryDB(Long id, Long totalOfRevamount, Integer totalOfRevPackage, Integer totalOfLuckiestDraw, Long timeCreate) {
        this.id = id;
        this.totalOfRevamount = totalOfRevamount;
        this.totalOfRevPackage = totalOfRevPackage;
        this.totalOfLuckiestDraw = totalOfLuckiestDraw;
        this.timeCreate = timeCreate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTotalOfRevamount() {
        return totalOfRevamount;
    }

    public void setTotalOfRevamount(Long totalOfRevamount) {
        this.totalOfRevamount = totalOfRevamount;
    }

    public Integer getTotalOfRevPackage() {
        return totalOfRevPackage;
    }

    public void setTotalOfRevPackage(Integer totalOfRevPackage) {
        this.totalOfRevPackage = totalOfRevPackage;
    }

    public Integer getTotalOfLuckiestDraw() {
        return totalOfLuckiestDraw;
    }

    public void setTotalOfLuckiestDraw(Integer totalOfLuckiestDraw) {
        this.totalOfLuckiestDraw = totalOfLuckiestDraw;
    }

    public Long getTimeCreate() {
        return timeCreate;
    }

    public void setTimeCreate(Long timeCreate) {
        this.timeCreate = timeCreate;
    }

}
