package vn.com.vng.zalopay.data.cache.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RECEIVE_PACKAGE_GD".
 */
public class ReceivePackageGD {

    private long id;
    private Long packageId;
    private String sendZaloPayID;
    private String sendFullName;
    private Long amount;
    private Long openedTime;

    public ReceivePackageGD() {
    }

    public ReceivePackageGD(long id) {
        this.id = id;
    }

    public ReceivePackageGD(long id, Long packageId, String sendZaloPayID, String sendFullName, Long amount, Long openedTime) {
        this.id = id;
        this.packageId = packageId;
        this.sendZaloPayID = sendZaloPayID;
        this.sendFullName = sendFullName;
        this.amount = amount;
        this.openedTime = openedTime;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Long getPackageId() {
        return packageId;
    }

    public void setPackageId(Long packageId) {
        this.packageId = packageId;
    }

    public String getSendZaloPayID() {
        return sendZaloPayID;
    }

    public void setSendZaloPayID(String sendZaloPayID) {
        this.sendZaloPayID = sendZaloPayID;
    }

    public String getSendFullName() {
        return sendFullName;
    }

    public void setSendFullName(String sendFullName) {
        this.sendFullName = sendFullName;
    }

    public Long getAmount() {
        return amount;
    }

    public void setAmount(Long amount) {
        this.amount = amount;
    }

    public Long getOpenedTime() {
        return openedTime;
    }

    public void setOpenedTime(Long openedTime) {
        this.openedTime = openedTime;
    }

}
