package vn.com.vng.zalopay.data.cache.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import vn.com.vng.zalopay.data.cache.model.RedPacketAppInfoGD;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RED_PACKET_APP_INFO_GD".
*/
public class RedPacketAppInfoGDDao extends AbstractDao<RedPacketAppInfoGD, Long> {

    public static final String TABLENAME = "RED_PACKET_APP_INFO_GD";

    /**
     * Properties of entity RedPacketAppInfoGD.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Checksum = new Property(1, String.class, "checksum", false, "CHECKSUM");
        public final static Property ExpiredTime = new Property(2, Long.class, "expiredTime", false, "EXPIRED_TIME");
        public final static Property MinAmounTeach = new Property(3, Long.class, "minAmounTeach", false, "MIN_AMOUN_TEACH");
        public final static Property MaxTotalAmountPerBundle = new Property(4, Long.class, "maxTotalAmountPerBundle", false, "MAX_TOTAL_AMOUNT_PER_BUNDLE");
        public final static Property MaxPackageQuantity = new Property(5, Integer.class, "maxPackageQuantity", false, "MAX_PACKAGE_QUANTITY");
        public final static Property MaxCountHist = new Property(6, Integer.class, "maxCountHist", false, "MAX_COUNT_HIST");
        public final static Property MaxMessageLength = new Property(7, Integer.class, "maxMessageLength", false, "MAX_MESSAGE_LENGTH");
        public final static Property BundleExpiredTime = new Property(8, Long.class, "bundleExpiredTime", false, "BUNDLE_EXPIRED_TIME");
        public final static Property MinDivideAmount = new Property(9, Long.class, "minDivideAmount", false, "MIN_DIVIDE_AMOUNT");
    };


    public RedPacketAppInfoGDDao(DaoConfig config) {
        super(config);
    }
    
    public RedPacketAppInfoGDDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RED_PACKET_APP_INFO_GD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CHECKSUM\" TEXT," + // 1: checksum
                "\"EXPIRED_TIME\" INTEGER," + // 2: expiredTime
                "\"MIN_AMOUN_TEACH\" INTEGER," + // 3: minAmounTeach
                "\"MAX_TOTAL_AMOUNT_PER_BUNDLE\" INTEGER," + // 4: maxTotalAmountPerBundle
                "\"MAX_PACKAGE_QUANTITY\" INTEGER," + // 5: maxPackageQuantity
                "\"MAX_COUNT_HIST\" INTEGER," + // 6: maxCountHist
                "\"MAX_MESSAGE_LENGTH\" INTEGER," + // 7: maxMessageLength
                "\"BUNDLE_EXPIRED_TIME\" INTEGER," + // 8: bundleExpiredTime
                "\"MIN_DIVIDE_AMOUNT\" INTEGER);"); // 9: minDivideAmount
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RED_PACKET_APP_INFO_GD\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RedPacketAppInfoGD entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String checksum = entity.getChecksum();
        if (checksum != null) {
            stmt.bindString(2, checksum);
        }
 
        Long expiredTime = entity.getExpiredTime();
        if (expiredTime != null) {
            stmt.bindLong(3, expiredTime);
        }
 
        Long minAmounTeach = entity.getMinAmounTeach();
        if (minAmounTeach != null) {
            stmt.bindLong(4, minAmounTeach);
        }
 
        Long maxTotalAmountPerBundle = entity.getMaxTotalAmountPerBundle();
        if (maxTotalAmountPerBundle != null) {
            stmt.bindLong(5, maxTotalAmountPerBundle);
        }
 
        Integer maxPackageQuantity = entity.getMaxPackageQuantity();
        if (maxPackageQuantity != null) {
            stmt.bindLong(6, maxPackageQuantity);
        }
 
        Integer maxCountHist = entity.getMaxCountHist();
        if (maxCountHist != null) {
            stmt.bindLong(7, maxCountHist);
        }
 
        Integer maxMessageLength = entity.getMaxMessageLength();
        if (maxMessageLength != null) {
            stmt.bindLong(8, maxMessageLength);
        }
 
        Long bundleExpiredTime = entity.getBundleExpiredTime();
        if (bundleExpiredTime != null) {
            stmt.bindLong(9, bundleExpiredTime);
        }
 
        Long minDivideAmount = entity.getMinDivideAmount();
        if (minDivideAmount != null) {
            stmt.bindLong(10, minDivideAmount);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RedPacketAppInfoGD readEntity(Cursor cursor, int offset) {
        RedPacketAppInfoGD entity = new RedPacketAppInfoGD( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // checksum
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // expiredTime
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // minAmounTeach
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // maxTotalAmountPerBundle
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // maxPackageQuantity
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // maxCountHist
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // maxMessageLength
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // bundleExpiredTime
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9) // minDivideAmount
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RedPacketAppInfoGD entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setChecksum(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setExpiredTime(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setMinAmounTeach(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setMaxTotalAmountPerBundle(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setMaxPackageQuantity(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setMaxCountHist(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setMaxMessageLength(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setBundleExpiredTime(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setMinDivideAmount(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RedPacketAppInfoGD entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RedPacketAppInfoGD entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
