package vn.com.vng.zalopay.data.cache.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RED_PACKAGE_ITEM_GD".
 */
public class RedPackageItemGD implements vn.com.vng.zalopay.domain.model.IPersistentObject {

    private Long id;
    private String zpTransID;
    private Long bundleID;
    private Integer state;

    public RedPackageItemGD() {
    }

    public RedPackageItemGD(Long id) {
        this.id = id;
    }

    public RedPackageItemGD(Long id, String zpTransID, Long bundleID, Integer state) {
        this.id = id;
        this.zpTransID = zpTransID;
        this.bundleID = bundleID;
        this.state = state;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getZpTransID() {
        return zpTransID;
    }

    public void setZpTransID(String zpTransID) {
        this.zpTransID = zpTransID;
    }

    public Long getBundleID() {
        return bundleID;
    }

    public void setBundleID(Long bundleID) {
        this.bundleID = bundleID;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

}
