package vn.com.vng.zalopay.data.cache.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "RED_PACKET_APP_INFO_GD".
 */
@Entity
public class RedPacketAppInfoGD {

    @Id(autoincrement = true)
    public Long id;
    public String checksum;
    public Long expiredTime;
    public Long minAmounTeach;
    public Long maxTotalAmountPerBundle;
    public Integer maxPackageQuantity;
    public Integer maxCountHist;
    public Integer maxMessageLength;
    public Long bundleExpiredTime;
    public Long minDivideAmount;

    @Generated
    public RedPacketAppInfoGD() {
    }

    public RedPacketAppInfoGD(Long id) {
        this.id = id;
    }

    @Generated
    public RedPacketAppInfoGD(Long id, String checksum, Long expiredTime, Long minAmounTeach, Long maxTotalAmountPerBundle, Integer maxPackageQuantity, Integer maxCountHist, Integer maxMessageLength, Long bundleExpiredTime, Long minDivideAmount) {
        this.id = id;
        this.checksum = checksum;
        this.expiredTime = expiredTime;
        this.minAmounTeach = minAmounTeach;
        this.maxTotalAmountPerBundle = maxTotalAmountPerBundle;
        this.maxPackageQuantity = maxPackageQuantity;
        this.maxCountHist = maxCountHist;
        this.maxMessageLength = maxMessageLength;
        this.bundleExpiredTime = bundleExpiredTime;
        this.minDivideAmount = minDivideAmount;
    }

}
