package vn.com.vng.zalopay.data.cache.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SENT_BUNDLE_SUMMARY_DB".
 */
@Entity
public class SentBundleSummaryDB {

    @Id
    public Long id;
    public Long totalOfSentAmount;
    public Long totalOfSentBundle;
    public Long timeCreate;


}
