package vn.com.vng.zalopay.data.cache.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SENT_PACKAGE_GD".
 */
public class SentPackageGD {

    private long id;
    private String revZaloPayID;
    private Long revZaloID;
    private String revFullName;
    private String revAvatarURL;
    private Long openTime;
    private Long amount;
    private String sendMessage;
    private Integer isLuckiest;

    public SentPackageGD() {
    }

    public SentPackageGD(long id) {
        this.id = id;
    }

    public SentPackageGD(long id, String revZaloPayID, Long revZaloID, String revFullName, String revAvatarURL, Long openTime, Long amount, String sendMessage, Integer isLuckiest) {
        this.id = id;
        this.revZaloPayID = revZaloPayID;
        this.revZaloID = revZaloID;
        this.revFullName = revFullName;
        this.revAvatarURL = revAvatarURL;
        this.openTime = openTime;
        this.amount = amount;
        this.sendMessage = sendMessage;
        this.isLuckiest = isLuckiest;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getRevZaloPayID() {
        return revZaloPayID;
    }

    public void setRevZaloPayID(String revZaloPayID) {
        this.revZaloPayID = revZaloPayID;
    }

    public Long getRevZaloID() {
        return revZaloID;
    }

    public void setRevZaloID(Long revZaloID) {
        this.revZaloID = revZaloID;
    }

    public String getRevFullName() {
        return revFullName;
    }

    public void setRevFullName(String revFullName) {
        this.revFullName = revFullName;
    }

    public String getRevAvatarURL() {
        return revAvatarURL;
    }

    public void setRevAvatarURL(String revAvatarURL) {
        this.revAvatarURL = revAvatarURL;
    }

    public Long getOpenTime() {
        return openTime;
    }

    public void setOpenTime(Long openTime) {
        this.openTime = openTime;
    }

    public Long getAmount() {
        return amount;
    }

    public void setAmount(Long amount) {
        this.amount = amount;
    }

    public String getSendMessage() {
        return sendMessage;
    }

    public void setSendMessage(String sendMessage) {
        this.sendMessage = sendMessage;
    }

    public Integer getIsLuckiest() {
        return isLuckiest;
    }

    public void setIsLuckiest(Integer isLuckiest) {
        this.isLuckiest = isLuckiest;
    }

}
