package vn.com.vng.zalopay.data.cache.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TRANSFER_RECENT".
 */
@Entity
public class TransferRecent {

    @Id
    public String zaloPayId;
    public String zaloPayName;
    public String displayName;
    public String avatar;
    public String phoneNumber;
    public Integer transferType;
    public Long amount;
    public String message;
    public Long timeCreate;

    @Generated
    public TransferRecent() {
    }

    public TransferRecent(String zaloPayId) {
        this.zaloPayId = zaloPayId;
    }

    @Generated
    public TransferRecent(String zaloPayId, String zaloPayName, String displayName, String avatar, String phoneNumber, Integer transferType, Long amount, String message, Long timeCreate) {
        this.zaloPayId = zaloPayId;
        this.zaloPayName = zaloPayName;
        this.displayName = displayName;
        this.avatar = avatar;
        this.phoneNumber = phoneNumber;
        this.transferType = transferType;
        this.amount = amount;
        this.message = message;
        this.timeCreate = timeCreate;
    }

}
