package vn.com.vng.zalopay.data.cache.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import vn.com.vng.zalopay.data.cache.model.TransactionLog;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TRANSACTION_LOG".
*/
public class TransactionLogDao extends AbstractDao<TransactionLog, Long> {

    public static final String TABLENAME = "TRANSACTION_LOG";

    /**
     * Properties of entity TransactionLog.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Transid = new Property(0, long.class, "transid", true, "TRANSID");
        public final static Property Appid = new Property(1, long.class, "appid", false, "APPID");
        public final static Property Platform = new Property(2, String.class, "platform", false, "PLATFORM");
        public final static Property Description = new Property(3, String.class, "description", false, "DESCRIPTION");
        public final static Property Pmcid = new Property(4, Integer.class, "pmcid", false, "PMCID");
        public final static Property Reqdate = new Property(5, Long.class, "reqdate", false, "REQDATE");
        public final static Property Grossamount = new Property(6, Integer.class, "grossamount", false, "GROSSAMOUNT");
        public final static Property Netamount = new Property(7, Integer.class, "netamount", false, "NETAMOUNT");
        public final static Property Type = new Property(8, Integer.class, "type", false, "TYPE");
    };


    public TransactionLogDao(DaoConfig config) {
        super(config);
    }
    
    public TransactionLogDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TRANSACTION_LOG\" (" + //
                "\"TRANSID\" INTEGER PRIMARY KEY NOT NULL UNIQUE ," + // 0: transid
                "\"APPID\" INTEGER NOT NULL ," + // 1: appid
                "\"PLATFORM\" TEXT," + // 2: platform
                "\"DESCRIPTION\" TEXT," + // 3: description
                "\"PMCID\" INTEGER," + // 4: pmcid
                "\"REQDATE\" INTEGER," + // 5: reqdate
                "\"GROSSAMOUNT\" INTEGER," + // 6: grossamount
                "\"NETAMOUNT\" INTEGER," + // 7: netamount
                "\"TYPE\" INTEGER);"); // 8: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TRANSACTION_LOG\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TransactionLog entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getTransid());
        stmt.bindLong(2, entity.getAppid());
 
        String platform = entity.getPlatform();
        if (platform != null) {
            stmt.bindString(3, platform);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(4, description);
        }
 
        Integer pmcid = entity.getPmcid();
        if (pmcid != null) {
            stmt.bindLong(5, pmcid);
        }
 
        Long reqdate = entity.getReqdate();
        if (reqdate != null) {
            stmt.bindLong(6, reqdate);
        }
 
        Integer grossamount = entity.getGrossamount();
        if (grossamount != null) {
            stmt.bindLong(7, grossamount);
        }
 
        Integer netamount = entity.getNetamount();
        if (netamount != null) {
            stmt.bindLong(8, netamount);
        }
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(9, type);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TransactionLog readEntity(Cursor cursor, int offset) {
        TransactionLog entity = new TransactionLog( //
            cursor.getLong(offset + 0), // transid
            cursor.getLong(offset + 1), // appid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // platform
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // description
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // pmcid
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // reqdate
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // grossamount
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // netamount
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8) // type
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TransactionLog entity, int offset) {
        entity.setTransid(cursor.getLong(offset + 0));
        entity.setAppid(cursor.getLong(offset + 1));
        entity.setPlatform(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDescription(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPmcid(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setReqdate(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setGrossamount(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setNetamount(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setType(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TransactionLog entity, long rowId) {
        entity.setTransid(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TransactionLog entity) {
        if(entity != null) {
            return entity.getTransid();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
