package vn.com.vng.zalopay.data.cache.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TRANSACTION_LOG".
 */
public class TransactionLog {

    private long transid;
    private long appid;
    private String userid;
    private String appuser;
    private String platform;
    private String description;
    private Integer pmcid;
    private Long reqdate;
    private Integer userchargeamt;
    private Integer userfeeamt;
    private Integer amount;
    private Integer type;

    public TransactionLog() {
    }

    public TransactionLog(long transid) {
        this.transid = transid;
    }

    public TransactionLog(long transid, long appid, String userid, String appuser, String platform, String description, Integer pmcid, Long reqdate, Integer userchargeamt, Integer userfeeamt, Integer amount, Integer type) {
        this.transid = transid;
        this.appid = appid;
        this.userid = userid;
        this.appuser = appuser;
        this.platform = platform;
        this.description = description;
        this.pmcid = pmcid;
        this.reqdate = reqdate;
        this.userchargeamt = userchargeamt;
        this.userfeeamt = userfeeamt;
        this.amount = amount;
        this.type = type;
    }

    public long getTransid() {
        return transid;
    }

    public void setTransid(long transid) {
        this.transid = transid;
    }

    public long getAppid() {
        return appid;
    }

    public void setAppid(long appid) {
        this.appid = appid;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getAppuser() {
        return appuser;
    }

    public void setAppuser(String appuser) {
        this.appuser = appuser;
    }

    public String getPlatform() {
        return platform;
    }

    public void setPlatform(String platform) {
        this.platform = platform;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getPmcid() {
        return pmcid;
    }

    public void setPmcid(Integer pmcid) {
        this.pmcid = pmcid;
    }

    public Long getReqdate() {
        return reqdate;
    }

    public void setReqdate(Long reqdate) {
        this.reqdate = reqdate;
    }

    public Integer getUserchargeamt() {
        return userchargeamt;
    }

    public void setUserchargeamt(Integer userchargeamt) {
        this.userchargeamt = userchargeamt;
    }

    public Integer getUserfeeamt() {
        return userfeeamt;
    }

    public void setUserfeeamt(Integer userfeeamt) {
        this.userfeeamt = userfeeamt;
    }

    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
