package vn.com.vng.zalopay.data.cache.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ZALO_FRIEND_GD".
*/
public class ZaloFriendGDDao extends AbstractDao<ZaloFriendGD, Long> {

    public static final String TABLENAME = "ZALO_FRIEND_GD";

    /**
     * Properties of entity ZaloFriendGD.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UserName = new Property(0, String.class, "userName", false, "USER_NAME");
        public final static Property DisplayName = new Property(1, String.class, "displayName", false, "DISPLAY_NAME");
        public final static Property Avatar = new Property(2, String.class, "avatar", false, "AVATAR");
        public final static Property UserGender = new Property(3, Long.class, "userGender", false, "USER_GENDER");
        public final static Property Birthday = new Property(4, String.class, "birthday", false, "BIRTHDAY");
        public final static Property UsingApp = new Property(5, Boolean.class, "usingApp", false, "USING_APP");
        public final static Property Fulltextsearch = new Property(6, String.class, "fulltextsearch", false, "FULLTEXTSEARCH");
        public final static Property ZaloId = new Property(7, long.class, "zaloId", true, "_id");
    }

    private DaoSession daoSession;


    public ZaloFriendGDDao(DaoConfig config) {
        super(config);
    }
    
    public ZaloFriendGDDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ZALO_FRIEND_GD\" (" + //
                "\"USER_NAME\" TEXT," + // 0: userName
                "\"DISPLAY_NAME\" TEXT," + // 1: displayName
                "\"AVATAR\" TEXT," + // 2: avatar
                "\"USER_GENDER\" INTEGER," + // 3: userGender
                "\"BIRTHDAY\" TEXT," + // 4: birthday
                "\"USING_APP\" INTEGER," + // 5: usingApp
                "\"FULLTEXTSEARCH\" TEXT," + // 6: fulltextsearch
                "\"_id\" INTEGER PRIMARY KEY NOT NULL );"); // 7: zaloId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ZALO_FRIEND_GD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ZaloFriendGD entity) {
        stmt.clearBindings();
 
        String userName = entity.userName;
        if (userName != null) {
            stmt.bindString(1, userName);
        }
 
        String displayName = entity.displayName;
        if (displayName != null) {
            stmt.bindString(2, displayName);
        }
 
        String avatar = entity.avatar;
        if (avatar != null) {
            stmt.bindString(3, avatar);
        }
 
        Long userGender = entity.userGender;
        if (userGender != null) {
            stmt.bindLong(4, userGender);
        }
 
        String birthday = entity.birthday;
        if (birthday != null) {
            stmt.bindString(5, birthday);
        }
 
        Boolean usingApp = entity.usingApp;
        if (usingApp != null) {
            stmt.bindLong(6, usingApp ? 1L: 0L);
        }
 
        String fulltextsearch = entity.fulltextsearch;
        if (fulltextsearch != null) {
            stmt.bindString(7, fulltextsearch);
        }
        stmt.bindLong(8, entity.zaloId);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ZaloFriendGD entity) {
        stmt.clearBindings();
 
        String userName = entity.userName;
        if (userName != null) {
            stmt.bindString(1, userName);
        }
 
        String displayName = entity.displayName;
        if (displayName != null) {
            stmt.bindString(2, displayName);
        }
 
        String avatar = entity.avatar;
        if (avatar != null) {
            stmt.bindString(3, avatar);
        }
 
        Long userGender = entity.userGender;
        if (userGender != null) {
            stmt.bindLong(4, userGender);
        }
 
        String birthday = entity.birthday;
        if (birthday != null) {
            stmt.bindString(5, birthday);
        }
 
        Boolean usingApp = entity.usingApp;
        if (usingApp != null) {
            stmt.bindLong(6, usingApp ? 1L: 0L);
        }
 
        String fulltextsearch = entity.fulltextsearch;
        if (fulltextsearch != null) {
            stmt.bindString(7, fulltextsearch);
        }
        stmt.bindLong(8, entity.zaloId);
    }

    @Override
    protected final void attachEntity(ZaloFriendGD entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 7);
    }    

    @Override
    public ZaloFriendGD readEntity(Cursor cursor, int offset) {
        ZaloFriendGD entity = new ZaloFriendGD();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ZaloFriendGD entity, int offset) {
        entity.userName = cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
        entity.displayName = cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1);
        entity.avatar = cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2);
        entity.userGender = cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3);
        entity.birthday = cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4);
        entity.usingApp = cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0;
        entity.fulltextsearch = cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6);
        entity.zaloId = cursor.getLong(offset + 7);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ZaloFriendGD entity, long rowId) {
        entity.zaloId = rowId;
        return rowId;
    }
    
    @Override
    public Long getKey(ZaloFriendGD entity) {
        if(entity != null) {
            return entity.zaloId;
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ZaloFriendGD entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getZaloPayProfileGDDao().getAllColumns());
            builder.append(" FROM ZALO_FRIEND_GD T");
            builder.append(" LEFT JOIN ZALO_PAY_PROFILE_GD T0 ON T.\"_id\"=T0.\"ZALO_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ZaloFriendGD loadCurrentDeep(Cursor cursor, boolean lock) {
        ZaloFriendGD entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        ZaloPayProfileGD zaloPayInfo = loadCurrentOther(daoSession.getZaloPayProfileGDDao(), cursor, offset);
         if(zaloPayInfo != null) {
            entity.setZaloPayInfo(zaloPayInfo);
        }

        return entity;    
    }

    public ZaloFriendGD loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ZaloFriendGD> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ZaloFriendGD> list = new ArrayList<ZaloFriendGD>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ZaloFriendGD> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ZaloFriendGD> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
