package vn.com.vng.zalopay.data.cache.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "RED_PACKET_APP_INFO_GD".
 */
@Entity
public class RedPacketAppInfoGD {

    @Id(autoincrement = true)
    public Long id;
    public String checksum;
    public Long expiredTime;
    public Long minAmountEach;
    public Long maxTotalAmountPerBundle;
    public Long maxPackageQuantity;
    public Long maxCountHist;
    public Long maxMessageLength;
    public Long bundleExpiredTime;
    public Long minDivideAmount;
    public Long maxAmountPerPackage;


}
