package vn.com.vng.zalopay.data.cache.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TRANSACTION_LOG".
 */
@Entity
public class TransactionLog {

    @Id
    @Unique
    public long transid;
    public long appid;
    public String userid;
    public String appuser;
    public String platform;
    public String description;
    public Long pmcid;
    public Long reqdate;
    public Long userchargeamt;
    public Long userfeeamt;
    public Long amount;
    public Long type;
    public Long sign;
    public String username;
    public String appusername;
    public Long statustype;


}
