package vn.com.vng.zalopay.data.cache.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ZPC".
 */
@Entity
public class ZPC {

    @Id(autoincrement = true)
    public Long id;

    @Unique
    public long zaloId;

    @Unique
    public long zalopayId;

    @Unique
    public String phoneNumber;

    @Unique
    public String zalopayName;
    public String avatar;
    public String displayName;
    public String normalizeDisplayName;
    public long status;


}
