package vn.com.vng.zalopay.monitors;

/**
 * Created by huuhoa on 6/27/17.
 * Monitor events
 */

public enum ZPMonitorEvent {
    TIMING_SDK_START,
    TIMING_SDK_START_ACTIVITY,
    TIMING_SDK_RENDER_DYNAMICITEMDETAIL,
    TIMING_SDK_RENDER_APPINFO,
    TIMING_SDK_RENDER_TOTALAMOUNTANDFEE,
    TIMING_SDK_ADD_PAYMENTCHANNEL,
    TIMING_SDK_RENDER_ORDERINFO,
    TIMING_SDK_LOAD_APPINFO_START,
    TIMING_SDK_LOAD_APPINFO_END,
    TIMING_SDK_LOAD_BANKLIST_START,
    TIMING_SDK_LOAD_BANKLIST_END,
    TIMING_SDK_LOAD_CARDLIST_START,
    TIMING_SDK_LOAD_CARDLIST_END,
    TIMING_SDK_LOAD_PLATFORMINFO,
    TIMING_SDK_DOWNLOAD_RESOURCE,
    TIMING_SDK_INIT_RESOURCE,
}
