package vn.com.vng.zalopay.monitors;

/**
 * Created by huuhoa on 6/27/17.
 * Monitor events
 */

public enum ZPMonitorEvent {
    TIMING_SDK_START,
    TIMING_SDK_START_ACTIVITY,
    TIMING_SDK_RENDER_DYNAMICITEMDETAIL,
    TIMING_SDK_RENDER_TOTALAMOUNTANDFEE,
    TIMING_SDK_ADD_PAYMENTCHANNEL,
    TIMING_SDK_RENDER_ORDERINFO,
    TIMING_SDK_LOAD_APPINFO_START,
    TIMING_SDK_LOAD_APPINFO_END,
    TIMING_SDK_LOAD_BANKLIST_START,
    TIMING_SDK_LOAD_BANKLIST_END,
    TIMING_SDK_LOAD_CARDLIST_START,
    TIMING_SDK_LOAD_CARDLIST_END,
    TIMING_SDK_LOAD_PLATFORMINFO_START,
    TIMING_SDK_LOAD_PLATFORMINFO_END,
    TIMING_SDK_DOWNLOAD_RESOURCE_START,
    TIMING_SDK_DOWNLOAD_RESOURCE_END,
    TIMING_SDK_INIT_RESOURCE_START,
    TIMING_SDK_INIT_RESOURCE_END,
    TIMING_SDK_ON_SUBSCRIBE_START,
    TIMING_SDK_ON_SUBSCRIBE,
    TIMING_SDK_ON_INFO_READY,
    TIMING_SDK_ON_PAYMENT_READY,
    TIMING_SDK_START_CHANNEL_LIST_PRESENTER,
    TIMING_ZPC_LOAD_START,
    TIMING_ZPC_LOAD_UCB_START,
    TIMING_ZPC_LOAD_UCB_END,
    TIMING_ZPC_LOAD_ZALO_FRIEND_START,
    TIMING_ZPC_LOAD_ZALO_FRIEND_END,
    TIMING_ZPC_CALL_API_START,
    TIMING_ZPC_CALL_API_END,
    TIMING_ZPC_LOAD_END
}
