// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: zpmsguser.proto at 23:1
package vn.com.vng.zalopay.data.ws.protobuf;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum ServerMessageType implements WireEnum {
  AUTHEN_LOGIN_RESULT(1),

  PONG_CLIENT(2),

  KICK_OUT_USER(51),

  PUSH_NOTIFICATION(101);

  public static final ProtoAdapter<ServerMessageType> ADAPTER = ProtoAdapter.newEnumAdapter(ServerMessageType.class);

  private final int value;

  ServerMessageType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static ServerMessageType fromValue(int value) {
    switch (value) {
      case 1: return AUTHEN_LOGIN_RESULT;
      case 2: return PONG_CLIENT;
      case 51: return KICK_OUT_USER;
      case 101: return PUSH_NOTIFICATION;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
