// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zpmsguser.proto

package vn.com.vng.zalopay.data.ws.protobuf;

public final class ZPMsgProtos {
  private ZPMsgProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageSendUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.MessageSendUser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes data = 1;</code>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 1;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>required string signature = 2;</code>
     */
    boolean hasSignature();
    /**
     * <code>required string signature = 2;</code>
     */
    java.lang.String getSignature();
    /**
     * <code>required string signature = 2;</code>
     */
    com.google.protobuf.ByteString
        getSignatureBytes();

    /**
     * <code>optional int64 expiretime = 3;</code>
     */
    boolean hasExpiretime();
    /**
     * <code>optional int64 expiretime = 3;</code>
     */
    long getExpiretime();

    /**
     * <code>optional uint64 usrid = 4;</code>
     */
    boolean hasUsrid();
    /**
     * <code>optional uint64 usrid = 4;</code>
     */
    long getUsrid();
  }
  /**
   * Protobuf type {@code protobuf.MessageSendUser}
   */
  public static final class MessageSendUser extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.MessageSendUser)
      MessageSendUserOrBuilder {
    // Use MessageSendUser.newBuilder() to construct.
    private MessageSendUser(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageSendUser(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageSendUser defaultInstance;
    public static MessageSendUser getDefaultInstance() {
      return defaultInstance;
    }

    public MessageSendUser getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageSendUser(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              data_ = input.readBytes();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              signature_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              expiretime_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              usrid_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_MessageSendUser_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_MessageSendUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser.class, vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageSendUser> PARSER =
        new com.google.protobuf.AbstractParser<MessageSendUser>() {
      public MessageSendUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageSendUser(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageSendUser> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 1;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes data = 1;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private java.lang.Object signature_;
    /**
     * <code>required string signature = 2;</code>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string signature = 2;</code>
     */
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          signature_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string signature = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIRETIME_FIELD_NUMBER = 3;
    private long expiretime_;
    /**
     * <code>optional int64 expiretime = 3;</code>
     */
    public boolean hasExpiretime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 expiretime = 3;</code>
     */
    public long getExpiretime() {
      return expiretime_;
    }

    public static final int USRID_FIELD_NUMBER = 4;
    private long usrid_;
    /**
     * <code>optional uint64 usrid = 4;</code>
     */
    public boolean hasUsrid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 usrid = 4;</code>
     */
    public long getUsrid() {
      return usrid_;
    }

    private void initFields() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = "";
      expiretime_ = 0L;
      usrid_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSignature()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, data_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSignatureBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, expiretime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, usrid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSignatureBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, expiretime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, usrid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.MessageSendUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.MessageSendUser)
        vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_MessageSendUser_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_MessageSendUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser.class, vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser.Builder.class);
      }

      // Construct using vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        signature_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        expiretime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        usrid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_MessageSendUser_descriptor;
      }

      public vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser getDefaultInstanceForType() {
        return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser.getDefaultInstance();
      }

      public vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser build() {
        vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser buildPartial() {
        vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser result = new vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.signature_ = signature_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.expiretime_ = expiretime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.usrid_ = usrid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser) {
          return mergeFrom((vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser other) {
        if (other == vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser.getDefaultInstance()) return this;
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasSignature()) {
          bitField0_ |= 0x00000002;
          signature_ = other.signature_;
          onChanged();
        }
        if (other.hasExpiretime()) {
          setExpiretime(other.getExpiretime());
        }
        if (other.hasUsrid()) {
          setUsrid(other.getUsrid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasData()) {
          
          return false;
        }
        if (!hasSignature()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageSendUser) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 1;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes data = 1;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 1;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 1;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private java.lang.Object signature_ = "";
      /**
       * <code>required string signature = 2;</code>
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string signature = 2;</code>
       */
      public java.lang.String getSignature() {
        java.lang.Object ref = signature_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            signature_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string signature = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        java.lang.Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string signature = 2;</code>
       */
      public Builder setSignature(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string signature = 2;</code>
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000002);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      /**
       * <code>required string signature = 2;</code>
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        signature_ = value;
        onChanged();
        return this;
      }

      private long expiretime_ ;
      /**
       * <code>optional int64 expiretime = 3;</code>
       */
      public boolean hasExpiretime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 expiretime = 3;</code>
       */
      public long getExpiretime() {
        return expiretime_;
      }
      /**
       * <code>optional int64 expiretime = 3;</code>
       */
      public Builder setExpiretime(long value) {
        bitField0_ |= 0x00000004;
        expiretime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 expiretime = 3;</code>
       */
      public Builder clearExpiretime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        expiretime_ = 0L;
        onChanged();
        return this;
      }

      private long usrid_ ;
      /**
       * <code>optional uint64 usrid = 4;</code>
       */
      public boolean hasUsrid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint64 usrid = 4;</code>
       */
      public long getUsrid() {
        return usrid_;
      }
      /**
       * <code>optional uint64 usrid = 4;</code>
       */
      public Builder setUsrid(long value) {
        bitField0_ |= 0x00000008;
        usrid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 usrid = 4;</code>
       */
      public Builder clearUsrid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        usrid_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.MessageSendUser)
    }

    static {
      defaultInstance = new MessageSendUser(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.MessageSendUser)
  }

  public interface MessageLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.MessageLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint64 usrid = 1;</code>
     */
    boolean hasUsrid();
    /**
     * <code>required uint64 usrid = 1;</code>
     */
    long getUsrid();

    /**
     * <code>required string token = 2;</code>
     */
    boolean hasToken();
    /**
     * <code>required string token = 2;</code>
     */
    java.lang.String getToken();
    /**
     * <code>required string token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code protobuf.MessageLogin}
   */
  public static final class MessageLogin extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.MessageLogin)
      MessageLoginOrBuilder {
    // Use MessageLogin.newBuilder() to construct.
    private MessageLogin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageLogin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageLogin defaultInstance;
    public static MessageLogin getDefaultInstance() {
      return defaultInstance;
    }

    public MessageLogin getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              usrid_ = input.readUInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              token_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_MessageLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_MessageLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin.class, vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageLogin> PARSER =
        new com.google.protobuf.AbstractParser<MessageLogin>() {
      public MessageLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageLogin(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageLogin> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USRID_FIELD_NUMBER = 1;
    private long usrid_;
    /**
     * <code>required uint64 usrid = 1;</code>
     */
    public boolean hasUsrid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 usrid = 1;</code>
     */
    public long getUsrid() {
      return usrid_;
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private java.lang.Object token_;
    /**
     * <code>required string token = 2;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string token = 2;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      usrid_ = 0L;
      token_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUsrid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, usrid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTokenBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, usrid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTokenBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.MessageLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.MessageLogin)
        vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_MessageLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_MessageLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin.class, vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin.Builder.class);
      }

      // Construct using vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        usrid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_MessageLogin_descriptor;
      }

      public vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin getDefaultInstanceForType() {
        return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin.getDefaultInstance();
      }

      public vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin build() {
        vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin buildPartial() {
        vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin result = new vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.usrid_ = usrid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin) {
          return mergeFrom((vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin other) {
        if (other == vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin.getDefaultInstance()) return this;
        if (other.hasUsrid()) {
          setUsrid(other.getUsrid());
        }
        if (other.hasToken()) {
          bitField0_ |= 0x00000002;
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUsrid()) {
          
          return false;
        }
        if (!hasToken()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.MessageLogin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long usrid_ ;
      /**
       * <code>required uint64 usrid = 1;</code>
       */
      public boolean hasUsrid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 usrid = 1;</code>
       */
      public long getUsrid() {
        return usrid_;
      }
      /**
       * <code>required uint64 usrid = 1;</code>
       */
      public Builder setUsrid(long value) {
        bitField0_ |= 0x00000001;
        usrid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 usrid = 1;</code>
       */
      public Builder clearUsrid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        usrid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>required string token = 2;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string token = 2;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string token = 2;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 2;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        token_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.MessageLogin)
    }

    static {
      defaultInstance = new MessageLogin(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.MessageLogin)
  }

  public interface ResultAuthOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.ResultAuth)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint64 usrid = 1;</code>
     */
    boolean hasUsrid();
    /**
     * <code>required uint64 usrid = 1;</code>
     */
    long getUsrid();

    /**
     * <code>required int32 result = 2;</code>
     */
    boolean hasResult();
    /**
     * <code>required int32 result = 2;</code>
     */
    int getResult();

    /**
     * <code>optional int32 code = 3;</code>
     */
    boolean hasCode();
    /**
     * <code>optional int32 code = 3;</code>
     */
    int getCode();
  }
  /**
   * Protobuf type {@code protobuf.ResultAuth}
   */
  public static final class ResultAuth extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.ResultAuth)
      ResultAuthOrBuilder {
    // Use ResultAuth.newBuilder() to construct.
    private ResultAuth(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResultAuth(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResultAuth defaultInstance;
    public static ResultAuth getDefaultInstance() {
      return defaultInstance;
    }

    public ResultAuth getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResultAuth(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              usrid_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              result_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              code_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_ResultAuth_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_ResultAuth_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth.class, vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth.Builder.class);
    }

    public static com.google.protobuf.Parser<ResultAuth> PARSER =
        new com.google.protobuf.AbstractParser<ResultAuth>() {
      public ResultAuth parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResultAuth(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResultAuth> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USRID_FIELD_NUMBER = 1;
    private long usrid_;
    /**
     * <code>required uint64 usrid = 1;</code>
     */
    public boolean hasUsrid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 usrid = 1;</code>
     */
    public long getUsrid() {
      return usrid_;
    }

    public static final int RESULT_FIELD_NUMBER = 2;
    private int result_;
    /**
     * <code>required int32 result = 2;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 result = 2;</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int CODE_FIELD_NUMBER = 3;
    private int code_;
    /**
     * <code>optional int32 code = 3;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 code = 3;</code>
     */
    public int getCode() {
      return code_;
    }

    private void initFields() {
      usrid_ = 0L;
      result_ = 0;
      code_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUsrid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, usrid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, result_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, code_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, usrid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, result_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, code_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.ResultAuth}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.ResultAuth)
        vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuthOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_ResultAuth_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_ResultAuth_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth.class, vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth.Builder.class);
      }

      // Construct using vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        usrid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_ResultAuth_descriptor;
      }

      public vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth getDefaultInstanceForType() {
        return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth.getDefaultInstance();
      }

      public vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth build() {
        vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth buildPartial() {
        vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth result = new vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.usrid_ = usrid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.code_ = code_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth) {
          return mergeFrom((vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth other) {
        if (other == vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth.getDefaultInstance()) return this;
        if (other.hasUsrid()) {
          setUsrid(other.getUsrid());
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUsrid()) {
          
          return false;
        }
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.ResultAuth) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long usrid_ ;
      /**
       * <code>required uint64 usrid = 1;</code>
       */
      public boolean hasUsrid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 usrid = 1;</code>
       */
      public long getUsrid() {
        return usrid_;
      }
      /**
       * <code>required uint64 usrid = 1;</code>
       */
      public Builder setUsrid(long value) {
        bitField0_ |= 0x00000001;
        usrid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 usrid = 1;</code>
       */
      public Builder clearUsrid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        usrid_ = 0L;
        onChanged();
        return this;
      }

      private int result_ ;
      /**
       * <code>required int32 result = 2;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 result = 2;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>required int32 result = 2;</code>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000002;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 result = 2;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000002);
        result_ = 0;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>optional int32 code = 3;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 code = 3;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>optional int32 code = 3;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000004;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 code = 3;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        code_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.ResultAuth)
    }

    static {
      defaultInstance = new ResultAuth(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.ResultAuth)
  }

  public interface DataResponseUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.DataResponseUser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 msgtype = 1;</code>
     */
    boolean hasMsgtype();
    /**
     * <code>required int32 msgtype = 1;</code>
     */
    int getMsgtype();

    /**
     * <code>required bytes data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code protobuf.DataResponseUser}
   */
  public static final class DataResponseUser extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.DataResponseUser)
      DataResponseUserOrBuilder {
    // Use DataResponseUser.newBuilder() to construct.
    private DataResponseUser(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DataResponseUser(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DataResponseUser defaultInstance;
    public static DataResponseUser getDefaultInstance() {
      return defaultInstance;
    }

    public DataResponseUser getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DataResponseUser(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgtype_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_DataResponseUser_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_DataResponseUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser.class, vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser.Builder.class);
    }

    public static com.google.protobuf.Parser<DataResponseUser> PARSER =
        new com.google.protobuf.AbstractParser<DataResponseUser>() {
      public DataResponseUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataResponseUser(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DataResponseUser> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgtype_;
    /**
     * <code>required int32 msgtype = 1;</code>
     */
    public boolean hasMsgtype() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 msgtype = 1;</code>
     */
    public int getMsgtype() {
      return msgtype_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      msgtype_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsgtype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgtype_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgtype_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.DataResponseUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.DataResponseUser)
        vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_DataResponseUser_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_DataResponseUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser.class, vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser.Builder.class);
      }

      // Construct using vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgtype_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.internal_static_protobuf_DataResponseUser_descriptor;
      }

      public vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser getDefaultInstanceForType() {
        return vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser.getDefaultInstance();
      }

      public vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser build() {
        vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser buildPartial() {
        vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser result = new vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgtype_ = msgtype_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser) {
          return mergeFrom((vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser other) {
        if (other == vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser.getDefaultInstance()) return this;
        if (other.hasMsgtype()) {
          setMsgtype(other.getMsgtype());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgtype()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (vn.com.vng.zalopay.data.ws.protobuf.ZPMsgProtos.DataResponseUser) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgtype_ ;
      /**
       * <code>required int32 msgtype = 1;</code>
       */
      public boolean hasMsgtype() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 msgtype = 1;</code>
       */
      public int getMsgtype() {
        return msgtype_;
      }
      /**
       * <code>required int32 msgtype = 1;</code>
       */
      public Builder setMsgtype(int value) {
        bitField0_ |= 0x00000001;
        msgtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 msgtype = 1;</code>
       */
      public Builder clearMsgtype() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgtype_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.DataResponseUser)
    }

    static {
      defaultInstance = new DataResponseUser(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.DataResponseUser)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_MessageSendUser_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_MessageSendUser_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_MessageLogin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_MessageLogin_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_ResultAuth_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_ResultAuth_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_DataResponseUser_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_DataResponseUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017zpmsguser.proto\022\010protobuf\"U\n\017MessageSe" +
      "ndUser\022\014\n\004data\030\001 \002(\014\022\021\n\tsignature\030\002 \002(\t\022" +
      "\022\n\nexpiretime\030\003 \001(\003\022\r\n\005usrid\030\004 \001(\004\",\n\014Me" +
      "ssageLogin\022\r\n\005usrid\030\001 \002(\004\022\r\n\005token\030\002 \002(\t" +
      "\"9\n\nResultAuth\022\r\n\005usrid\030\001 \002(\004\022\016\n\006result\030" +
      "\002 \002(\005\022\014\n\004code\030\003 \001(\005\"1\n\020DataResponseUser\022" +
      "\017\n\007msgtype\030\001 \002(\005\022\014\n\004data\030\002 \002(\014B2\n#vn.com" +
      ".vng.zalopay.data.ws.protobufB\013ZPMsgProt" +
      "os"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_MessageSendUser_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_MessageSendUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_MessageSendUser_descriptor,
        new java.lang.String[] { "Data", "Signature", "Expiretime", "Usrid", });
    internal_static_protobuf_MessageLogin_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_MessageLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_MessageLogin_descriptor,
        new java.lang.String[] { "Usrid", "Token", });
    internal_static_protobuf_ResultAuth_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protobuf_ResultAuth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_ResultAuth_descriptor,
        new java.lang.String[] { "Usrid", "Result", "Code", });
    internal_static_protobuf_DataResponseUser_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protobuf_DataResponseUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_DataResponseUser_descriptor,
        new java.lang.String[] { "Msgtype", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
