// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: zpmsguser.proto at 155:1
package vn.com.vng.zalopay.data.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class MapResponseMessage extends Message<MapResponseMessage, MapResponseMessage.Builder> {
  public static final ProtoAdapter<MapResponseMessage> ADAPTER = new ProtoAdapter_MapResponseMessage();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_REQUESTID = 0L;

  public static final Integer DEFAULT_RESULTCODE = 0;

  public static final String DEFAULT_RESULTDATA = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64",
      label = WireField.Label.REQUIRED
  )
  public final Long requestid;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT32",
      label = WireField.Label.REQUIRED
  )
  public final Integer resultcode;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String resultdata;

  public MapResponseMessage(Long requestid, Integer resultcode, String resultdata) {
    this(requestid, resultcode, resultdata, ByteString.EMPTY);
  }

  public MapResponseMessage(Long requestid, Integer resultcode, String resultdata, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.requestid = requestid;
    this.resultcode = resultcode;
    this.resultdata = resultdata;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.requestid = requestid;
    builder.resultcode = resultcode;
    builder.resultdata = resultdata;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof MapResponseMessage)) return false;
    MapResponseMessage o = (MapResponseMessage) other;
    return unknownFields().equals(o.unknownFields())
        && requestid.equals(o.requestid)
        && resultcode.equals(o.resultcode)
        && Internal.equals(resultdata, o.resultdata);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + requestid.hashCode();
      result = result * 37 + resultcode.hashCode();
      result = result * 37 + (resultdata != null ? resultdata.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", requestid=").append(requestid);
    builder.append(", resultcode=").append(resultcode);
    if (resultdata != null) builder.append(", resultdata=").append(resultdata);
    return builder.replace(0, 2, "MapResponseMessage{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<MapResponseMessage, Builder> {
    public Long requestid;

    public Integer resultcode;

    public String resultdata;

    public Builder() {
    }

    public Builder requestid(Long requestid) {
      this.requestid = requestid;
      return this;
    }

    public Builder resultcode(Integer resultcode) {
      this.resultcode = resultcode;
      return this;
    }

    public Builder resultdata(String resultdata) {
      this.resultdata = resultdata;
      return this;
    }

    @Override
    public MapResponseMessage build() {
      if (requestid == null
          || resultcode == null) {
        throw Internal.missingRequiredFields(requestid, "requestid",
            resultcode, "resultcode");
      }
      return new MapResponseMessage(requestid, resultcode, resultdata, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_MapResponseMessage extends ProtoAdapter<MapResponseMessage> {
    ProtoAdapter_MapResponseMessage() {
      super(FieldEncoding.LENGTH_DELIMITED, MapResponseMessage.class);
    }

    @Override
    public int encodedSize(MapResponseMessage value) {
      return ProtoAdapter.UINT64.encodedSizeWithTag(1, value.requestid)
          + ProtoAdapter.INT32.encodedSizeWithTag(2, value.resultcode)
          + (value.resultdata != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.resultdata) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, MapResponseMessage value) throws IOException {
      ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.requestid);
      ProtoAdapter.INT32.encodeWithTag(writer, 2, value.resultcode);
      if (value.resultdata != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.resultdata);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public MapResponseMessage decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.requestid(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.resultcode(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.resultdata(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public MapResponseMessage redact(MapResponseMessage value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
