// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: zpmsguser.proto at 31:1
package vn.com.vng.zalopay.data.protobuf;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * Define type of message that client sends to server
 * Zalo Pay: 2.0
 */
public enum MessageType implements WireEnum {
  AUTHEN_LOGIN(1),

  FEEDBACK(2),

  PING_SERVER(3),

  MSG_TO_USER_REQUEST(4),

  RECOVERY_REQUEST(5),

  /**
   * available from Zalo Pay 2.10
   */
  PAYMENT_REQUEST(6);

  public static final ProtoAdapter<MessageType> ADAPTER = ProtoAdapter.newEnumAdapter(MessageType.class);

  private final int value;

  MessageType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static MessageType fromValue(int value) {
    switch (value) {
      case 1: return AUTHEN_LOGIN;
      case 2: return FEEDBACK;
      case 3: return PING_SERVER;
      case 4: return MSG_TO_USER_REQUEST;
      case 5: return RECOVERY_REQUEST;
      case 6: return PAYMENT_REQUEST;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
