// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: zpmsguser.proto at 194:1
package vn.com.vng.zalopay.data.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * Zalo Pay: 2.10
 */
public final class NameValuePair extends Message<NameValuePair, NameValuePair.Builder> {
  public static final ProtoAdapter<NameValuePair> ADAPTER = new ProtoAdapter_NameValuePair();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_NAME = "";

  public static final String DEFAULT_VALUE = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REQUIRED
  )
  public final String name;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REQUIRED
  )
  public final String value;

  public NameValuePair(String name, String value) {
    this(name, value, ByteString.EMPTY);
  }

  public NameValuePair(String name, String value, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.name = name;
    this.value = value;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.name = name;
    builder.value = value;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof NameValuePair)) return false;
    NameValuePair o = (NameValuePair) other;
    return unknownFields().equals(o.unknownFields())
        && name.equals(o.name)
        && value.equals(o.value);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + name.hashCode();
      result = result * 37 + value.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", name=").append(name);
    builder.append(", value=").append(value);
    return builder.replace(0, 2, "NameValuePair{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<NameValuePair, Builder> {
    public String name;

    public String value;

    public Builder() {
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder value(String value) {
      this.value = value;
      return this;
    }

    @Override
    public NameValuePair build() {
      if (name == null
          || value == null) {
        throw Internal.missingRequiredFields(name, "name",
            value, "value");
      }
      return new NameValuePair(name, value, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_NameValuePair extends ProtoAdapter<NameValuePair> {
    ProtoAdapter_NameValuePair() {
      super(FieldEncoding.LENGTH_DELIMITED, NameValuePair.class);
    }

    @Override
    public int encodedSize(NameValuePair value) {
      return ProtoAdapter.STRING.encodedSizeWithTag(1, value.name)
          + ProtoAdapter.STRING.encodedSizeWithTag(2, value.value)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, NameValuePair value) throws IOException {
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name);
      ProtoAdapter.STRING.encodeWithTag(writer, 2, value.value);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public NameValuePair decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.name(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.value(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public NameValuePair redact(NameValuePair value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
