// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: zpmsguser.proto at 149:1
package vn.com.vng.zalopay.data.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PairKeyValue extends Message<PairKeyValue, PairKeyValue.Builder> {
  public static final ProtoAdapter<PairKeyValue> ADAPTER = new ProtoAdapter_PairKeyValue();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_KEY = "";

  public static final String DEFAULT_VALUE = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REQUIRED
  )
  public final String key;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REQUIRED
  )
  public final String value;

  public PairKeyValue(String key, String value) {
    this(key, value, ByteString.EMPTY);
  }

  public PairKeyValue(String key, String value, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.key = key;
    this.value = value;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.key = key;
    builder.value = value;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PairKeyValue)) return false;
    PairKeyValue o = (PairKeyValue) other;
    return unknownFields().equals(o.unknownFields())
        && key.equals(o.key)
        && value.equals(o.value);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + key.hashCode();
      result = result * 37 + value.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", key=").append(key);
    builder.append(", value=").append(value);
    return builder.replace(0, 2, "PairKeyValue{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PairKeyValue, Builder> {
    public String key;

    public String value;

    public Builder() {
    }

    public Builder key(String key) {
      this.key = key;
      return this;
    }

    public Builder value(String value) {
      this.value = value;
      return this;
    }

    @Override
    public PairKeyValue build() {
      if (key == null
          || value == null) {
        throw Internal.missingRequiredFields(key, "key",
            value, "value");
      }
      return new PairKeyValue(key, value, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PairKeyValue extends ProtoAdapter<PairKeyValue> {
    ProtoAdapter_PairKeyValue() {
      super(FieldEncoding.LENGTH_DELIMITED, PairKeyValue.class);
    }

    @Override
    public int encodedSize(PairKeyValue value) {
      return ProtoAdapter.STRING.encodedSizeWithTag(1, value.key)
          + ProtoAdapter.STRING.encodedSizeWithTag(2, value.value)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PairKeyValue value) throws IOException {
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.key);
      ProtoAdapter.STRING.encodeWithTag(writer, 2, value.value);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PairKeyValue decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.key(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.value(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PairKeyValue redact(PairKeyValue value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
