// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: zpmsguser.proto at 37:1
package vn.com.vng.zalopay.data.protobuf;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum RecoveryOrder implements WireEnum {
  ORDER_DESCEND(0),

  ORDER_ASCEND(1);

  public static final ProtoAdapter<RecoveryOrder> ADAPTER = ProtoAdapter.newEnumAdapter(RecoveryOrder.class);

  private final int value;

  RecoveryOrder(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static RecoveryOrder fromValue(int value) {
    switch (value) {
      case 0: return ORDER_DESCEND;
      case 1: return ORDER_ASCEND;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
